#!/usr/bin/env node
/**
 * Prerenders published articles to real static files at blog/<slug>.html.
 *
 * Why this exists: blog/post.html is a "Loading..." shell that fetches and renders
 * the article client-side. That content is invisible to Bing and to every LLM
 * answer engine, and only reaches Google after a render-queue delay. Baking the
 * title, meta, canonical, JSON-LD, and article body into a real file fixes all of
 * that at once. It also removes the need for the /blog/:slug rewrite — Netlify's
 * extension resolution serves blog/<slug>.html for /blog/<slug> directly.
 *
 * The generated pages still load blog.js, which detects the baked content
 * (data-prerendered="1" on #post-body), skips its fetch/render path, and applies
 * only the progressive enhancements: table of contents, mid-article CTA, related
 * posts, share buttons.
 *
 * Run: node scripts/prerender-blog.mjs
 * Wired into the Netlify build command in netlify.toml.
 */

import { readFileSync, writeFileSync, readdirSync, unlinkSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { marked } from 'marked';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const BLOG_DIR = join(ROOT, 'blog');

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://vhpmmfhfwnpmavytoomd.supabase.co';
// Anon key. Not a secret — the identical key already ships in the client bundle.
// Env first so there is one place to rotate it; literal fallback so a build
// without the env var still works.
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY
  || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZocG1tZmhmd25wbWF2eXRvb21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1OTgyMDYsImV4cCI6MjA4NTE3NDIwNn0.6JmfnTTR8onr3ZgFpzdZa4BbVBraUyePVEUHOJgxmuk';
const SITE_URL = process.env.SITE_URL || 'https://royaltyapp.ai';
const APP_ID = process.env.ROYALTY_APP_ID || 'd0229946-0812-4a96-acc4-0344613ee8b1';

// Marks a file as ours so cleanup never deletes a hand-written page.
const GENERATED_MARKER = '<!-- generated by scripts/prerender-blog.mjs -->';

// Content that must never reach a published page. These are the importer's
// working annotations; if one shows up here the draft was imported unstripped
// (see Royalty-SEO/scripts/import_drafts.py) and publishing it would leak
// editorial notes and placeholder stats to readers.
const FORBIDDEN_IN_BODY = [
  { label: 'REVIEW_CHECKLIST comment', re: /REVIEW_CHECKLIST/i },
  { label: 'HUMAN_EDIT prompt', re: /HUMAN_EDIT/i },
  { label: 'Meta Title metadata block', re: /\*\*Meta Title\*\*\s*:/i },
  { label: 'Meta Description metadata block', re: /\*\*Meta Description\*\*\s*:/i },
  { label: 'Target Keyword metadata block', re: /\*\*Target Keyword\*\*\s*:/i },
  { label: 'humanness_score annotation', re: /humanness_score/i },
];

async function rpc(fn, body) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`, {
    method: 'POST',
    headers: {
      'apikey': SUPABASE_ANON_KEY,
      'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    throw new Error(`${fn} failed: ${res.status} ${await res.text()}`);
  }
  return res.json();
}

/**
 * Hero image metadata for every published article, keyed by slug.
 *
 * og_image_alt / og_image_credit / og_image_credit_url are columns on
 * newsletter_articles that get_article_by_slug does not return, so they are
 * read straight from the table. Anon can already SELECT published articles
 * (that is how blog.js works), and a read-only select for three columns is a
 * far smaller change than replacing that RPC's body.
 *
 * Never throws: a hero image is decoration, and losing it must not take the
 * whole prerender down with it.
 */
async function fetchHeroMeta() {
  const params = new URLSearchParams({
    select: 'slug,og_image_url,og_image_alt,og_image_credit,og_image_credit_url',
    app_id: `eq.${APP_ID}`,
    status: 'eq.published',
    deleted_at: 'is.null',
  });
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/newsletter_articles?${params}`, {
      headers: {
        'apikey': SUPABASE_ANON_KEY,
        'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
      },
    });
    if (!res.ok) {
      console.warn(`  [hero] skipped — ${res.status} reading image columns`);
      return new Map();
    }
    return new Map((await res.json()).map((r) => [r.slug, r]));
  } catch (e) {
    console.warn(`  [hero] skipped — ${e.message}`);
    return new Map();
  }
}

function escapeHtml(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Escape for embedding inside a JSON-LD <script> block. */
function jsonLd(obj) {
  // </script> inside a JSON string would close the block early.
  return JSON.stringify(obj, null, 2).replace(/<\//g, '<\\/');
}

function toIsoDate(value) {
  if (!value) return '';
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? '' : d.toISOString();
}

function formatDate(value) {
  if (!value) return '';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return '';
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

/**
 * Drops a leading "# Heading" from the body.
 *
 * The drafts open with the article title as an H1, but the title is also its own
 * column and is rendered into <h1 class="post-title">. Parsing the body as-is
 * gives the page two H1s and prints the headline twice.
 */
function stripLeadingH1(markdown) {
  return String(markdown || '').replace(/^\s*#\s+\S[^\n]*\n+/, '');
}

/** Plain-text excerpt, used when an article has no meta_description. */
function excerpt(markdown, max = 155) {
  const text = String(markdown || '')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/[#>*_`|-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  if (text.length <= max) return text;
  return `${text.slice(0, max - 1).replace(/\s+\S*$/, '')}…`;
}

/**
 * Reads blog/post.html and splits it into the shell around #post-body, so the
 * generated pages inherit the real chrome and CSS without duplicating them here.
 */
function loadTemplate() {
  const html = readFileSync(join(BLOG_DIR, 'post.html'), 'utf-8');

  const bodyOpenRe = /<div class="post-content" id="post-body">/;
  const match = html.match(bodyOpenRe);
  if (!match) {
    throw new Error('Could not find #post-body in blog/post.html — template changed?');
  }
  const bodyStart = match.index + match[0].length;
  const bodyEnd = html.indexOf('</div>', bodyStart);
  if (bodyEnd === -1) {
    throw new Error('Could not find the close of #post-body in blog/post.html');
  }

  return {
    head: html.slice(0, match.index),
    bodyOpenTag: match[0],
    tail: html.slice(bodyEnd),
  };
}

/**
 * The hero <img>, plus a credit line when we know who took the photo.
 *
 * alt falls back to '' rather than to the article title: an empty alt marks the
 * image as decorative, which is honest, whereas repeating the headline makes a
 * screen reader read it twice and describes nothing.
 */
function heroHtml(article) {
  const alt = article.og_image_alt || '';
  const credit = article.og_image_credit;
  const creditUrl = article.og_image_credit_url;

  const creditHtml = credit
    ? `\n                    <figcaption class="post-hero-credit">Photo: ${
        creditUrl
          ? `<a href="${escapeHtml(creditUrl)}" rel="nofollow noopener" target="_blank">${escapeHtml(credit)}</a>`
          : escapeHtml(credit)
      }</figcaption>`
    : '';

  return `<figure class="post-hero" id="post-hero">
                    <img id="post-hero-img" src="${escapeHtml(article.og_image_url)}" alt="${escapeHtml(alt)}" loading="eager">${creditHtml}
                </figure>`;
}

function buildPage(template, article) {
  const title = article.meta_title || article.title;
  const description = article.meta_description || excerpt(article.content);
  const url = `${SITE_URL}/blog/${article.slug}`;
  const image = article.og_image_url || `${SITE_URL}/og-image.png`;
  const published = toIsoDate(article.published_at);
  const modified = toIsoDate(article.updated_at || article.published_at);
  const bodyHtml = marked.parse(stripLeadingH1(article.content));
  const tags = article.tags || article.seo_keywords || [];

  const articleSchema = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: article.title,
    description,
    image,
    url,
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    datePublished: published || undefined,
    dateModified: modified || undefined,
    author: { '@type': 'Organization', name: 'Royalty', url: `${SITE_URL}/` },
    publisher: {
      '@type': 'Organization',
      name: 'Royalty',
      url: `${SITE_URL}/`,
      logo: { '@type': 'ImageObject', url: `${SITE_URL}/logo.svg` },
    },
    keywords: tags.length ? tags.join(', ') : undefined,
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE_URL}/` },
      { '@type': 'ListItem', position: 2, name: 'Blog', item: `${SITE_URL}/blog/` },
      { '@type': 'ListItem', position: 3, name: article.title, item: url },
    ],
  };

  // Rebuild the <head> with baked values instead of the shell's empty placeholders.
  let head = template.head
    // post.html carries noindex because its own URL is a "Loading..." shell.
    // Generated article pages are real content and must be indexable.
    .replace(/\s*<!-- This file is the client-render shell[\s\S]*?-->\n/, '\n')
    .replace(/\s*<meta name="robots" content="noindex, nofollow">\n/, '\n')
    .replace(
      /<title>[\s\S]*?<\/title>/,
      `<title>${escapeHtml(title)} - Royalty Blog</title>`
    )
    .replace(
      /<meta name="description" content="[^"]*">/,
      `<meta name="description" content="${escapeHtml(description)}">`
    )
    .replace(
      /<meta property="og:title" content="[^"]*">/,
      `<meta property="og:title" content="${escapeHtml(article.title)}">`
    )
    .replace(
      /<meta property="og:description" content="[^"]*">/,
      `<meta property="og:description" content="${escapeHtml(description)}">`
    )
    .replace(
      /<meta property="og:image" content="[^"]*">/,
      `<meta property="og:image" content="${escapeHtml(image)}">`
    )
    .replace(
      /<meta property="og:url" content="[^"]*">/,
      `<meta property="og:url" content="${escapeHtml(url)}">`
    )
    .replace(
      /<meta name="twitter:title" content="[^"]*">/,
      `<meta name="twitter:title" content="${escapeHtml(article.title)}">`
    )
    .replace(
      /<meta name="twitter:description" content="[^"]*">/,
      `<meta name="twitter:description" content="${escapeHtml(description)}">`
    )
    .replace(
      /<meta name="twitter:image" content="[^"]*">/,
      `<meta name="twitter:image" content="${escapeHtml(image)}">`
    );

  const injected = `${GENERATED_MARKER}
    <link rel="canonical" href="${escapeHtml(article.canonical_url || url)}">
    <script type="application/ld+json">
${jsonLd(articleSchema)}
    </script>
    <script type="application/ld+json">
${jsonLd(breadcrumbSchema)}
    </script>
</head>`;

  head = head.replace('</head>', injected);

  // Bake the visible header too — title and date are part of what a crawler reads.
  head = head
    .replace(
      /(<h1 class="post-title" id="post-title">)([\s\S]*?)(<\/h1>)/,
      `$1${escapeHtml(article.title)}$3`
    )
    .replace(
      /(<span class="post-date" id="post-date">)([\s\S]*?)(<\/span>)/,
      `$1${escapeHtml(formatDate(article.published_at))}$3`
    )
    .replace(
      /(<span class="post-industry" id="post-industry">)([\s\S]*?)(<\/span>)/,
      `$1${escapeHtml(article.primary_topic || article.industry || '')}$3`
    )
    // The shell hides the article until JS reveals it. Prerendered pages must be
    // visible with JS disabled, so drop the inline display:none.
    .replace(
      /(<article class="post-page" id="post-content")\s+style="display:\s*none;?"/,
      '$1'
    );

  // Bake the hero image in too. blog.js sets #post-hero client-side, but it
  // bails out early on a prerendered page (see the data-prerendered check in
  // renderPost), so on these pages that code never runs — without this the
  // hero stays display:none and the article has no image at all.
  head = head.replace(
    /<div class="post-hero" id="post-hero"[^>]*>[\s\S]*?<\/div>/,
    article.og_image_url ? heroHtml(article) : ''
  );

  // data-article-id lets blog.js exclude this article from its own related-posts
  // query without another round trip.
  const bodyOpenTag = template.bodyOpenTag.replace(
    'id="post-body"',
    `id="post-body" data-prerendered="1" data-article-id="${escapeHtml(article.id || '')}"`
  );

  return `${head}${bodyOpenTag}\n${bodyHtml}\n                ${template.tail}`;
}

/** Refuses to write a page carrying importer annotations. */
function assertClean(article, bodyMarkdown) {
  const problems = FORBIDDEN_IN_BODY
    .filter(({ re }) => re.test(bodyMarkdown))
    .map(({ label }) => label);
  if (problems.length) {
    throw new Error(
      `article "${article.slug}" still contains: ${problems.join(', ')}. ` +
      `Fix parse_draft() in Royalty-SEO/scripts/import_drafts.py and re-import — do not publish this.`
    );
  }
}

/** Removes generated files whose article is no longer published. */
function cleanupStale(keepSlugs) {
  if (!existsSync(BLOG_DIR)) return 0;
  let removed = 0;
  for (const name of readdirSync(BLOG_DIR)) {
    if (!name.endsWith('.html')) continue;
    if (name === 'post.html' || name === 'index.html') continue;
    const slug = name.slice(0, -5);
    if (keepSlugs.has(slug)) continue;

    const path = join(BLOG_DIR, name);
    // Only ever delete files this script wrote.
    if (!readFileSync(path, 'utf-8').includes(GENERATED_MARKER)) continue;
    unlinkSync(path);
    console.log(`  removed stale ${name}`);
    removed++;
  }
  return removed;
}

async function main() {
  const listed = await rpc('get_published_articles', {
    p_app_id: APP_ID,
    p_language: 'en',
    p_topic: null,
    p_limit: 200,
  });
  const articles = (Array.isArray(listed) ? listed : listed?.articles) || [];

  if (articles.length === 0) {
    console.log('No published articles — nothing to prerender.');
    cleanupStale(new Set());
    return;
  }

  const template = loadTemplate();
  const heroMeta = await fetchHeroMeta();
  const slugs = new Set();
  let written = 0;
  const failures = [];

  for (const summary of articles) {
    const slug = summary.slug;
    if (!slug) continue;

    try {
      // The list RPC returns summaries; the body only comes from the detail RPC.
      const detail = await rpc('get_article_by_slug', {
        p_app_id: APP_ID,
        p_slug: slug,
        p_language: summary.language || 'en',
      });
      const article = detail?.article || detail;
      if (!article || !article.content) {
        throw new Error('no content returned');
      }

      // The detail RPC predates the hero-image columns, so merge them in here.
      Object.assign(article, heroMeta.get(slug) || {});

      assertClean(article, article.content);

      writeFileSync(join(BLOG_DIR, `${slug}.html`), buildPage(template, article), 'utf-8');
      slugs.add(slug);
      written++;
      console.log(`  wrote blog/${slug}.html`);
    } catch (err) {
      // One bad article must not cost every other article its static page.
      failures.push(`${slug}: ${err.message}`);
      console.error(`  SKIPPED ${slug} — ${err.message}`);
    }
  }

  cleanupStale(slugs);
  console.log(`Prerendered ${written}/${articles.length} article(s).`);

  if (failures.length) {
    console.error(`\n${failures.length} article(s) failed:`);
    failures.forEach(f => console.error(`  - ${f}`));
    process.exitCode = 1;
  }
}

main().catch(err => {
  console.error('Prerender failed:', err);
  process.exit(1);
});
