-- =====================================================
-- PIN HASHING MIGRATION: Client SHA-256 → Server bcrypt
-- CRITICAL SECURITY FIX
-- =====================================================
-- Problem:
--   - Hardcoded salt 'automata_salt' visible in client JS
--   - SHA-256 is fast (GPU-crackable for 4-digit PINs)
--   - Two client implementations: Base64 (app.js) and Hex (index.html)
--
-- Solution:
--   - bcrypt with cost factor 10 (slow, brute-force resistant)
--   - Per-user random salt (generated by bcrypt)
--   - Server-side hashing (salt never leaves database)
--   - Dual-check migration: bcrypt first, legacy SHA-256 fallback, auto-upgrade
-- =====================================================

-- 1. Enable pgcrypto extension for crypt() and gen_salt()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Add pin_hash_version column to track hash format
-- 'bcrypt' = new secure format
-- 'legacy_base64' = old SHA-256 with Base64 encoding (from app.js)
-- 'legacy_hex' = old SHA-256 with Hex encoding (from index.html)
-- NULL = no PIN set
ALTER TABLE app_members
ADD COLUMN IF NOT EXISTS pin_hash_version TEXT DEFAULT NULL;

-- Mark all existing non-null hashes as legacy (we'll determine exact format during verification)
UPDATE app_members
SET pin_hash_version = 'legacy'
WHERE pin_hash IS NOT NULL AND pin_hash_version IS NULL;

-- 3. Create helper function to hash PIN with bcrypt
CREATE OR REPLACE FUNCTION hash_pin_bcrypt(p_pin TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Use blowfish (bf) with cost factor 10
    -- Cost 10 = ~100ms per hash, good balance of security and speed
    RETURN crypt(p_pin, gen_salt('bf', 10));
END;
$$;

-- 4. Create helper function to verify bcrypt PIN
CREATE OR REPLACE FUNCTION verify_pin_bcrypt(p_pin TEXT, p_hash TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF p_hash IS NULL OR p_pin IS NULL THEN
        RETURN FALSE;
    END IF;
    -- bcrypt stores salt in the hash itself, so we just crypt and compare
    RETURN crypt(p_pin, p_hash) = p_hash;
END;
$$;

-- 5. Create helper function to verify legacy SHA-256 PIN
-- Handles both Base64 and Hex formats
CREATE OR REPLACE FUNCTION verify_pin_legacy_sha256(p_pin TEXT, p_hash TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_data BYTEA;
    v_sha256 BYTEA;
    v_base64 TEXT;
    v_hex TEXT;
BEGIN
    IF p_hash IS NULL OR p_pin IS NULL THEN
        RETURN FALSE;
    END IF;

    -- Compute SHA-256 of pin + salt (matching client-side logic)
    v_data := convert_to(p_pin || 'automata_salt', 'UTF8');
    v_sha256 := digest(v_data, 'sha256');

    -- Try Base64 format (from app.js)
    v_base64 := encode(v_sha256, 'base64');
    IF v_base64 = p_hash THEN
        RETURN TRUE;
    END IF;

    -- Try Hex format (from index.html)
    v_hex := encode(v_sha256, 'hex');
    IF v_hex = p_hash THEN
        RETURN TRUE;
    END IF;

    RETURN FALSE;
END;
$$;

-- 6. Create function to upgrade legacy hash to bcrypt
-- Called after successful legacy verification
CREATE OR REPLACE FUNCTION upgrade_pin_to_bcrypt(p_member_id UUID, p_pin TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE app_members
    SET
        pin_hash = hash_pin_bcrypt(p_pin),
        pin_hash_version = 'bcrypt'
    WHERE id = p_member_id;
END;
$$;

-- 7. Update customer_app_signup to receive plaintext PIN and hash server-side
-- IMPORTANT: Parameter changes from p_pin_hash to p_pin
DROP FUNCTION IF EXISTS customer_app_signup(UUID, TEXT, TEXT, TEXT, TEXT, TEXT);

CREATE OR REPLACE FUNCTION customer_app_signup(
    p_app_id UUID,
    p_first_name TEXT,
    p_last_name TEXT,
    p_email TEXT,
    p_phone TEXT DEFAULT NULL,
    p_pin TEXT DEFAULT NULL  -- Changed from p_pin_hash - now receives plaintext
)
RETURNS TABLE (
    success BOOLEAN,
    member_id UUID,
    customer_id UUID,
    welcome_points INTEGER,
    error_message TEXT
) AS $$
DECLARE
    v_app RECORD;
    v_customer_id UUID;
    v_member_id UUID;
    v_welcome_points INTEGER;
    v_existing_member UUID;
    v_pin_hash TEXT;
    v_pin_version TEXT;
BEGIN
    -- Get app and validate
    SELECT * INTO v_app
    FROM customer_apps
    WHERE id = p_app_id
      AND is_published = true
      AND is_active = true
      AND deleted_at IS NULL;

    IF NOT FOUND THEN
        RETURN QUERY SELECT false, NULL::UUID, NULL::UUID, NULL::INTEGER, 'App not found or not published'::TEXT;
        RETURN;
    END IF;

    -- Check for existing member with this email
    SELECT id INTO v_existing_member
    FROM app_members
    WHERE app_id = p_app_id AND email = lower(p_email) AND deleted_at IS NULL;

    IF FOUND THEN
        RETURN QUERY SELECT false, NULL::UUID, NULL::UUID, NULL::INTEGER, 'Email already registered. Please log in instead.'::TEXT;
        RETURN;
    END IF;

    -- Check for existing member with this phone (if phone provided)
    IF p_phone IS NOT NULL AND p_phone != '' THEN
        SELECT id INTO v_existing_member
        FROM app_members
        WHERE app_id = p_app_id AND phone = p_phone AND deleted_at IS NULL;

        IF FOUND THEN
            RETURN QUERY SELECT false, NULL::UUID, NULL::UUID, NULL::INTEGER, 'Phone number already registered. Please use a different number or log in.'::TEXT;
            RETURN;
        END IF;
    END IF;

    -- Hash the PIN server-side with bcrypt (if provided)
    IF p_pin IS NOT NULL AND LENGTH(p_pin) > 0 THEN
        v_pin_hash := hash_pin_bcrypt(p_pin);
        v_pin_version := 'bcrypt';
    ELSE
        v_pin_hash := NULL;
        v_pin_version := NULL;
    END IF;

    -- Get welcome points from settings
    v_welcome_points := COALESCE((v_app.settings->>'welcome_points')::INTEGER, 50);

    -- Create customer record in org's customers table
    INSERT INTO customers (
        organization_id,
        first_name,
        last_name,
        email,
        phone,
        source,
        tags
    ) VALUES (
        v_app.organization_id,
        p_first_name,
        p_last_name,
        lower(p_email),
        p_phone,
        'app',
        ARRAY['app-member']
    )
    RETURNING id INTO v_customer_id;

    -- Create app member record with bcrypt hash
    INSERT INTO app_members (
        app_id,
        customer_id,
        first_name,
        last_name,
        email,
        phone,
        display_name,
        pin_hash,
        pin_hash_version,  -- New column
        points_balance,
        total_points_earned,
        tier,
        profile_public,
        notifications_enabled
    ) VALUES (
        p_app_id,
        v_customer_id,
        p_first_name,
        p_last_name,
        lower(p_email),
        p_phone,
        p_first_name,
        v_pin_hash,
        v_pin_version,
        v_welcome_points,
        v_welcome_points,
        'bronze',
        false,
        true
    )
    RETURNING id INTO v_member_id;

    -- Create welcome points transaction
    INSERT INTO points_transactions (
        app_id,
        member_id,
        type,
        points_change,
        balance_after,
        description
    ) VALUES (
        p_app_id,
        v_member_id,
        'welcome',
        v_welcome_points,
        v_welcome_points,
        'Welcome bonus'
    );

    -- Create member_joined event
    INSERT INTO app_events (
        app_id,
        member_id,
        event_type,
        event_data
    ) VALUES (
        p_app_id,
        v_member_id,
        'member_joined',
        jsonb_build_object(
            'first_name', p_first_name,
            'email', lower(p_email),
            'welcome_points', v_welcome_points
        )
    );

    RETURN QUERY SELECT true, v_member_id, v_customer_id, v_welcome_points, NULL::TEXT;

EXCEPTION
    WHEN unique_violation THEN
        -- Check what constraint was violated
        IF SQLERRM LIKE '%phone%' THEN
            RETURN QUERY SELECT false, NULL::UUID, NULL::UUID, NULL::INTEGER, 'Phone number already registered. Please use a different number or log in.'::TEXT;
        ELSE
            RETURN QUERY SELECT false, NULL::UUID, NULL::UUID, NULL::INTEGER, 'Email already registered. Please log in instead.'::TEXT;
        END IF;
    WHEN OTHERS THEN
        RETURN QUERY SELECT false, NULL::UUID, NULL::UUID, NULL::INTEGER, ('Signup failed: ' || SQLERRM)::TEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute to anon users (for signup from customer app)
GRANT EXECUTE ON FUNCTION customer_app_signup(UUID, TEXT, TEXT, TEXT, TEXT, TEXT) TO anon, authenticated;

-- 8. Update verify_app_member_login with dual-check and auto-rehash
-- IMPORTANT: Parameter changes from p_pin_hash to p_pin
DROP FUNCTION IF EXISTS verify_app_member_login(UUID, TEXT, TEXT, TEXT);

CREATE OR REPLACE FUNCTION verify_app_member_login(
    p_app_id UUID,
    p_email TEXT DEFAULT NULL,
    p_phone TEXT DEFAULT NULL,
    p_pin TEXT DEFAULT NULL  -- Changed from p_pin_hash - now receives plaintext
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_member app_members%ROWTYPE;
    v_app customer_apps%ROWTYPE;
    v_identifier TEXT;
    v_is_allowed BOOLEAN;
    v_pin_verified BOOLEAN := FALSE;
BEGIN
    -- Validate input: need either email or phone
    IF p_email IS NULL AND p_phone IS NULL THEN
        RETURN jsonb_build_object(
            'success', false,
            'error_message', 'Email or phone required'
        );
    END IF;

    -- Validate PIN provided
    IF p_pin IS NULL OR LENGTH(p_pin) < 4 THEN
        RETURN jsonb_build_object(
            'success', false,
            'error_message', 'Invalid PIN'
        );
    END IF;

    -- Build identifier for rate limiting (app_id + email/phone)
    v_identifier := p_app_id::TEXT || ':' || COALESCE(LOWER(p_email), p_phone);

    -- Check rate limit: 5 attempts per 15 minutes
    v_is_allowed := check_and_record_rate_limit(v_identifier, 'member_login', 5, 15);

    IF NOT v_is_allowed THEN
        RETURN jsonb_build_object(
            'success', false,
            'error_message', 'Too many login attempts. Please try again in 15 minutes.',
            'rate_limited', true
        );
    END IF;

    -- Check app exists and is active
    SELECT * INTO v_app
    FROM customer_apps
    WHERE id = p_app_id
      AND is_active = true
      AND deleted_at IS NULL;

    IF v_app.id IS NULL THEN
        RETURN jsonb_build_object(
            'success', false,
            'error_message', 'App not found or inactive'
        );
    END IF;

    -- Find member by email or phone
    IF p_email IS NOT NULL THEN
        SELECT * INTO v_member
        FROM app_members
        WHERE app_id = p_app_id
          AND LOWER(email) = LOWER(p_email)
          AND deleted_at IS NULL;
    ELSE
        SELECT * INTO v_member
        FROM app_members
        WHERE app_id = p_app_id
          AND phone = p_phone
          AND deleted_at IS NULL;
    END IF;

    -- Member not found - use generic error (don't reveal account existence)
    IF v_member.id IS NULL THEN
        RETURN jsonb_build_object(
            'success', false,
            'error_message', 'Invalid credentials'
        );
    END IF;

    -- DUAL-CHECK: Try bcrypt first, fall back to legacy SHA-256
    IF v_member.pin_hash_version = 'bcrypt' THEN
        -- New accounts: verify with bcrypt only
        v_pin_verified := verify_pin_bcrypt(p_pin, v_member.pin_hash);
    ELSIF v_member.pin_hash_version IN ('legacy', 'legacy_base64', 'legacy_hex') THEN
        -- Legacy accounts: try SHA-256 formats
        v_pin_verified := verify_pin_legacy_sha256(p_pin, v_member.pin_hash);

        -- Auto-upgrade to bcrypt on successful login
        IF v_pin_verified THEN
            PERFORM upgrade_pin_to_bcrypt(v_member.id, p_pin);
        END IF;
    ELSE
        -- Unknown or NULL version - try bcrypt first, then legacy
        v_pin_verified := verify_pin_bcrypt(p_pin, v_member.pin_hash);

        IF NOT v_pin_verified THEN
            v_pin_verified := verify_pin_legacy_sha256(p_pin, v_member.pin_hash);

            -- Auto-upgrade if legacy matched
            IF v_pin_verified THEN
                PERFORM upgrade_pin_to_bcrypt(v_member.id, p_pin);
            END IF;
        END IF;
    END IF;

    -- PIN verification failed
    IF NOT v_pin_verified THEN
        RETURN jsonb_build_object(
            'success', false,
            'error_message', 'Invalid credentials'
        );
    END IF;

    -- Success! Update last_login_at
    UPDATE app_members
    SET last_login_at = NOW()
    WHERE id = v_member.id;

    RETURN jsonb_build_object(
        'success', true,
        'member_id', v_member.id,
        'display_name', v_member.display_name,
        'tier', v_member.tier,
        'points_balance', v_member.points_balance
    );
END;
$$;

-- Grant execute to anon (public login from customer app)
GRANT EXECUTE ON FUNCTION verify_app_member_login(UUID, TEXT, TEXT, TEXT) TO anon, authenticated;

-- Add comment
COMMENT ON FUNCTION verify_app_member_login IS
    'Securely verify member login with server-side PIN verification. '
    'Supports bcrypt (new) and legacy SHA-256 (auto-upgraded on success). '
    'Rate limited to 5 attempts per 15 minutes.';

-- 9. Grant execute on helper functions (for internal use only)
-- Note: These don't need anon access, they're called by the main functions
GRANT EXECUTE ON FUNCTION hash_pin_bcrypt(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION verify_pin_bcrypt(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION verify_pin_legacy_sha256(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION upgrade_pin_to_bcrypt(UUID, TEXT) TO authenticated;

-- 10. Add index for faster lookups by hash version (for monitoring migration progress)
CREATE INDEX IF NOT EXISTS idx_app_members_pin_hash_version
ON app_members(pin_hash_version)
WHERE pin_hash IS NOT NULL;

-- =====================================================
-- VERIFICATION QUERIES (run manually to check status)
-- =====================================================
-- Check migration progress:
-- SELECT
--     pin_hash_version,
--     COUNT(*) as count,
--     ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) as pct
-- FROM app_members
-- WHERE deleted_at IS NULL AND pin_hash IS NOT NULL
-- GROUP BY pin_hash_version
-- ORDER BY count DESC;
--
-- Expected: 'legacy' initially, gradually moves to 'bcrypt' as users log in
-- =====================================================
